function OutPut_K = G_SOC__Data_Merge(Out_Put_K)
%     OutPut_K.T_m_K_Grid =     [Out_Put_K.CS_1_K.T_m_K_Grid,         Out_Put_K.CS_2_K.T_m_K_Grid,         Out_Put_K.CS_3_K.T_m_K_Grid,          Out_Put_K.CS_4_K.T_m_K_Grid,           Out_Put_K.CS_5_K.T_m_K_Grid];
%     OutPut_K.W_m_K_Grid =    [Out_Put_K.CS_1_K.W_m_K_Grid,       Out_Put_K.CS_2_K.W_m_K_Grid,        Out_Put_K.CS_3_K.W_m_K_Grid,        Out_Put_K.CS_4_K.W_m_K_Grid,          Out_Put_K.CS_5_K.W_m_K_Grid];
    OutPut_K.T_m_Front_K_Grid =     [Out_Put_K.CS_1_K.T_m_Front_K_Grid,         Out_Put_K.CS_2_K.T_m_Front_K_Grid,         Out_Put_K.CS_3_K.T_m_Front_K_Grid,  Out_Put_K.CS_4_K.T_m_Front_K_Grid,  Out_Put_K.CS_5_K.T_m_Front_K_Grid, Out_Put_K.CS_6_K.T_m_Front_K_Grid, Out_Put_K.CS_7_K.T_m_Front_K_Grid, Out_Put_K.CS_8_K.T_m_Front_K_Grid, Out_Put_K.CS_9_K.T_m_Front_K_Grid, Out_Put_K.CS_10_K.T_m_Front_K_Grid, Out_Put_K.CS_11_K.T_m_Front_K_Grid];
    OutPut_K.W_m_Front_K_Grid =    [Out_Put_K.CS_1_K.W_m_Front_K_Grid,       Out_Put_K.CS_2_K.W_m_Front_K_Grid,        Out_Put_K.CS_3_K.W_m_Front_K_Grid,        Out_Put_K.CS_4_K.W_m_Front_K_Grid,          Out_Put_K.CS_5_K.W_m_Front_K_Grid,  Out_Put_K.CS_6_K.W_m_Front_K_Grid,       Out_Put_K.CS_7_K.W_m_Front_K_Grid,    Out_Put_K.CS_8_K.W_m_Front_K_Grid,      Out_Put_K.CS_9_K.W_m_Front_K_Grid,      Out_Put_K.CS_10_K.W_m_Front_K_Grid, Out_Put_K.CS_11_K.W_m_Front_K_Grid];
    OutPut_K.T_m_Rear_K_Grid =     [Out_Put_K.CS_1_K.T_m_Rear_K_Grid,         Out_Put_K.CS_2_K.T_m_Rear_K_Grid,         Out_Put_K.CS_3_K.T_m_Rear_K_Grid,          Out_Put_K.CS_4_K.T_m_Rear_K_Grid,           Out_Put_K.CS_5_K.T_m_Rear_K_Grid,  Out_Put_K.CS_6_K.T_m_Rear_K_Grid,         Out_Put_K.CS_7_K.T_m_Rear_K_Grid,         Out_Put_K.CS_8_K.T_m_Rear_K_Grid,          Out_Put_K.CS_9_K.T_m_Rear_K_Grid,           Out_Put_K.CS_10_K.T_m_Rear_K_Grid, Out_Put_K.CS_11_K.T_m_Rear_K_Grid];
    OutPut_K.W_m_Rear_K_Grid =    [Out_Put_K.CS_1_K.W_m_Rear_K_Grid,       Out_Put_K.CS_2_K.W_m_Rear_K_Grid,        Out_Put_K.CS_3_K.W_m_Rear_K_Grid,        Out_Put_K.CS_4_K.W_m_Rear_K_Grid,          Out_Put_K.CS_5_K.W_m_Rear_K_Grid, Out_Put_K.CS_6_K.W_m_Rear_K_Grid,       Out_Put_K.CS_7_K.W_m_Rear_K_Grid,        Out_Put_K.CS_8_K.W_m_Rear_K_Grid,        Out_Put_K.CS_9_K.W_m_Rear_K_Grid,          Out_Put_K.CS_10_K.W_m_Rear_K_Grid,  Out_Put_K.CS_11_K.W_m_Rear_K_Grid];
    
%     
%     OutPut_K.SOC_K_Grid =     [Out_Put_K.CS_1_K.SOC_K_Grid,        Out_Put_K.CS_2_K.SOC_K_Grid,         Out_Put_K.CS_3_K.SOC_K_Grid,         Out_Put_K.CS_4_K.SOC_K_Grid,           Out_Put_K.CS_5_K.SOC_K_Grid, ];
%     OutPut_K.SOC_K_1_Grid =  [Out_Put_K.CS_1_K.SOC_K_1_Grid,     Out_Put_K.CS_2_K.SOC_K_1_Grid,     Out_Put_K.CS_3_K.SOC_K_1_Grid,      Out_Put_K.CS_4_K.SOC_K_1_Grid,        Out_Put_K.CS_5_K.SOC_K_1_Grid];
%     OutPut_K.G_K_Grid =         [Out_Put_K.CS_1_K.G_K_Grid,             Out_Put_K.CS_2_K.G_K_Grid,            Out_Put_K.CS_3_K.G_K_Grid,             Out_Put_K.CS_4_K.G_K_Grid,                Out_Put_K.CS_5_K.G_K_Grid];
%     OutPut_K.G_K_1_Grid =      [Out_Put_K.CS_1_K.G_K_1_Grid,         Out_Put_K.CS_2_K.G_K_1_Grid,          Out_Put_K.CS_3_K.G_K_1_Grid,         Out_Put_K.CS_4_K.G_K_1_Grid,             Out_Put_K.CS_5_K.G_K_1_Grid];
%     OutPut_K.P_em_K_Grid =   [Out_Put_K.CS_1_K.P_em_K_Grid,       Out_Put_K.CS_2_K.P_em_K_Grid,       Out_Put_K.CS_3_K.P_em_K_Grid,       Out_Put_K.CS_4_K.P_em_K_Grid,          Out_Put_K.CS_5_K.P_em_K_Grid];
%     OutPut_K.Pb_K_Grid =       [Out_Put_K.CS_1_K.Pb_K_Grid,           Out_Put_K.CS_2_K.Pb_K_Grid,            Out_Put_K.CS_3_K.Pb_K_Grid,           Out_Put_K.CS_4_K.Pb_K_Grid,              Out_Put_K.CS_5_K.Pb_K_Grid];
%     OutPut_K.J_K_1_Grid =       [Out_Put_K.CS_1_K.J_K_1_Grid,           Out_Put_K.CS_2_K.J_K_1_Grid,           Out_Put_K.CS_3_K.J_K_1_Grid,          Out_Put_K.CS_4_K.J_K_1_Grid,              Out_Put_K.CS_5_K.J_K_1_Grid];
%     OutPut_K.M_K_1_Grid =     [Out_Put_K.CS_1_K.M_K_1_Grid,         Out_Put_K.CS_2_K.M_K_1_Grid,         Out_Put_K.CS_3_K.M_K_1_Grid,         Out_Put_K.CS_4_K.M_K_1_Grid,           Out_Put_K.CS_5_K.M_K_1_Grid];
%     OutPut_K.M_K_Grid =        [Out_Put_K.CS_1_K.M_K_Grid,            Out_Put_K.CS_2_K.M_K_Grid,            Out_Put_K.CS_3_K.M_K_Grid,            Out_Put_K.CS_4_K.M_K_Grid,               Out_Put_K.CS_5_K.M_K_Grid];
%     OutPut_K.Fuel_K_1_Grid =  [Out_Put_K.CS_1_K.Fuel_K_1_Grid,      Out_Put_K.CS_2_K.Fuel_K_1_Grid,     Out_Put_K.CS_3_K.Fuel_K_1_Grid,      Out_Put_K.CS_4_K.Fuel_K_1_Grid,        Out_Put_K.CS_5_K.Fuel_K_1_Grid];
    
    OutPut_K.SOC_K_Grid =     [Out_Put_K.CS_1_K.SOC_K_Grid,        Out_Put_K.CS_2_K.SOC_K_Grid,         Out_Put_K.CS_3_K.SOC_K_Grid,         Out_Put_K.CS_4_K.SOC_K_Grid,           Out_Put_K.CS_5_K.SOC_K_Grid, Out_Put_K.CS_6_K.SOC_K_Grid,        Out_Put_K.CS_7_K.SOC_K_Grid,         Out_Put_K.CS_8_K.SOC_K_Grid,         Out_Put_K.CS_9_K.SOC_K_Grid,           Out_Put_K.CS_10_K.SOC_K_Grid,  Out_Put_K.CS_11_K.SOC_K_Grid ];
    OutPut_K.SOC_K_1_Grid =  [Out_Put_K.CS_1_K.SOC_K_1_Grid,     Out_Put_K.CS_2_K.SOC_K_1_Grid,     Out_Put_K.CS_3_K.SOC_K_1_Grid,      Out_Put_K.CS_4_K.SOC_K_1_Grid,        Out_Put_K.CS_5_K.SOC_K_1_Grid, Out_Put_K.CS_6_K.SOC_K_1_Grid,     Out_Put_K.CS_7_K.SOC_K_1_Grid,     Out_Put_K.CS_8_K.SOC_K_1_Grid,      Out_Put_K.CS_9_K.SOC_K_1_Grid,        Out_Put_K.CS_10_K.SOC_K_1_Grid, Out_Put_K.CS_11_K.SOC_K_1_Grid];
    OutPut_K.G_K_Grid =         [Out_Put_K.CS_1_K.G_K_Grid,             Out_Put_K.CS_2_K.G_K_Grid,            Out_Put_K.CS_3_K.G_K_Grid,             Out_Put_K.CS_4_K.G_K_Grid,                Out_Put_K.CS_5_K.G_K_Grid, Out_Put_K.CS_6_K.G_K_Grid,             Out_Put_K.CS_7_K.G_K_Grid,            Out_Put_K.CS_8_K.G_K_Grid,             Out_Put_K.CS_9_K.G_K_Grid,                Out_Put_K.CS_10_K.G_K_Grid, Out_Put_K.CS_11_K.G_K_Grid];
    OutPut_K.G_K_1_Grid =      [Out_Put_K.CS_1_K.G_K_1_Grid,         Out_Put_K.CS_2_K.G_K_1_Grid,          Out_Put_K.CS_3_K.G_K_1_Grid,         Out_Put_K.CS_4_K.G_K_1_Grid,             Out_Put_K.CS_5_K.G_K_1_Grid, Out_Put_K.CS_6_K.G_K_1_Grid,         Out_Put_K.CS_7_K.G_K_1_Grid,          Out_Put_K.CS_8_K.G_K_1_Grid,         Out_Put_K.CS_9_K.G_K_1_Grid,             Out_Put_K.CS_10_K.G_K_1_Grid, Out_Put_K.CS_11_K.G_K_1_Grid];
    OutPut_K.P_em_K_Grid =   [Out_Put_K.CS_1_K.P_em_K_Grid,       Out_Put_K.CS_2_K.P_em_K_Grid,       Out_Put_K.CS_3_K.P_em_K_Grid,       Out_Put_K.CS_4_K.P_em_K_Grid,          Out_Put_K.CS_5_K.P_em_K_Grid, Out_Put_K.CS_6_K.P_em_K_Grid,       Out_Put_K.CS_7_K.P_em_K_Grid,       Out_Put_K.CS_8_K.P_em_K_Grid,       Out_Put_K.CS_9_K.P_em_K_Grid,          Out_Put_K.CS_10_K.P_em_K_Grid, Out_Put_K.CS_11_K.P_em_K_Grid];
    OutPut_K.Pb_K_Grid =       [Out_Put_K.CS_1_K.Pb_K_Grid,           Out_Put_K.CS_2_K.Pb_K_Grid,            Out_Put_K.CS_3_K.Pb_K_Grid,           Out_Put_K.CS_4_K.Pb_K_Grid,              Out_Put_K.CS_5_K.Pb_K_Grid, Out_Put_K.CS_6_K.Pb_K_Grid,           Out_Put_K.CS_7_K.Pb_K_Grid,            Out_Put_K.CS_8_K.Pb_K_Grid,           Out_Put_K.CS_9_K.Pb_K_Grid,              Out_Put_K.CS_10_K.Pb_K_Grid, Out_Put_K.CS_11_K.Pb_K_Grid];
    OutPut_K.J_K_1_Grid =       [Out_Put_K.CS_1_K.J_K_1_Grid,           Out_Put_K.CS_2_K.J_K_1_Grid,           Out_Put_K.CS_3_K.J_K_1_Grid,          Out_Put_K.CS_4_K.J_K_1_Grid,              Out_Put_K.CS_5_K.J_K_1_Grid, Out_Put_K.CS_6_K.J_K_1_Grid,           Out_Put_K.CS_7_K.J_K_1_Grid,           Out_Put_K.CS_8_K.J_K_1_Grid,          Out_Put_K.CS_9_K.J_K_1_Grid,              Out_Put_K.CS_10_K.J_K_1_Grid, Out_Put_K.CS_11_K.J_K_1_Grid];
    OutPut_K.M_K_1_Grid =     [Out_Put_K.CS_1_K.M_K_1_Grid,         Out_Put_K.CS_2_K.M_K_1_Grid,         Out_Put_K.CS_3_K.M_K_1_Grid,         Out_Put_K.CS_4_K.M_K_1_Grid,           Out_Put_K.CS_5_K.M_K_1_Grid, Out_Put_K.CS_6_K.M_K_1_Grid,         Out_Put_K.CS_7_K.M_K_1_Grid,         Out_Put_K.CS_8_K.M_K_1_Grid,         Out_Put_K.CS_9_K.M_K_1_Grid,           Out_Put_K.CS_10_K.M_K_1_Grid, Out_Put_K.CS_11_K.M_K_1_Grid];
    OutPut_K.M_K_Grid =        [Out_Put_K.CS_1_K.M_K_Grid,            Out_Put_K.CS_2_K.M_K_Grid,            Out_Put_K.CS_3_K.M_K_Grid,            Out_Put_K.CS_4_K.M_K_Grid,               Out_Put_K.CS_5_K.M_K_Grid, Out_Put_K.CS_6_K.M_K_Grid,            Out_Put_K.CS_7_K.M_K_Grid,            Out_Put_K.CS_8_K.M_K_Grid,            Out_Put_K.CS_9_K.M_K_Grid,               Out_Put_K.CS_10_K.M_K_Grid, Out_Put_K.CS_11_K.M_K_Grid];
    OutPut_K.Fuel_K_1_Grid =  [Out_Put_K.CS_1_K.Fuel_K_1_Grid,      Out_Put_K.CS_2_K.Fuel_K_1_Grid,     Out_Put_K.CS_3_K.Fuel_K_1_Grid,      Out_Put_K.CS_4_K.Fuel_K_1_Grid,        Out_Put_K.CS_5_K.Fuel_K_1_Grid, Out_Put_K.CS_6_K.Fuel_K_1_Grid,      Out_Put_K.CS_7_K.Fuel_K_1_Grid,     Out_Put_K.CS_8_K.Fuel_K_1_Grid,      Out_Put_K.CS_9_K.Fuel_K_1_Grid,        Out_Put_K.CS_10_K.Fuel_K_1_Grid, Out_Put_K.CS_11_K.Fuel_K_1_Grid];
end